// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplatedemo = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/demo/user/create": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "创建用户管理",
                "parameters": [
                    {
                        "description": "创建用户管理",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtouser.UserCreateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0,\"data\": \"ok\",\"msg\": \"success\"}",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/gincontext.DtoRender"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dtouser.UserCreateResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/demo/user/delete": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "删除用户管理",
                "parameters": [
                    {
                        "description": "删除用户管理",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtouser.UserDeleteReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0,\"data\": \"ok\",\"msg\": \"删除成功\"}",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/gincontext.DtoRender"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/demo/user/detail": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "用户管理详情",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID 数据自增 ID",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0,\"data\": \"ok\",\"msg\": \"success\"}",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/gincontext.DtoRender"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dtouser.UserDetailResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/demo/user/pageList": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "用户管理列表分页",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Page 页码",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "maximum": 1000,
                        "type": "integer",
                        "description": "PageSize 每页数据条数",
                        "name": "pageSize",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0,\"data\": \"ok\",\"msg\": \"success\"}",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/gincontext.DtoRender"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dtouser.UserPageListResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/demo/user/update": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "用户管理"
                ],
                "summary": "修改用户管理",
                "parameters": [
                    {
                        "description": "修改用户管理",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtouser.UserUpdateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0,\"data\": \"ok\",\"msg\": \"修改成功\"}",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/gincontext.DtoRender"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dtouser.UserCreateReq": {
            "type": "object",
            "properties": {
                "companyID": {
                    "description": "CompanyID 公司id",
                    "type": "integer"
                },
                "departmentID": {
                    "description": "DepartmentID 部门id",
                    "type": "integer"
                },
                "name": {
                    "description": "Name 姓名",
                    "type": "string"
                }
            }
        },
        "dtouser.UserCreateResp": {
            "type": "object",
            "properties": {
                "id": {
                    "description": "ID 数据自增 ID",
                    "type": "integer"
                }
            }
        },
        "dtouser.UserDeleteReq": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "description": "ID 数据自增 ID",
                    "type": "integer"
                }
            }
        },
        "dtouser.UserDetailResp": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "companyID": {
                    "description": "CompanyID 公司id",
                    "type": "integer"
                },
                "createdAt": {
                    "description": "CreatedAt 创建时间",
                    "type": "integer"
                },
                "createdBy": {
                    "description": "CreatedBy 创建人id",
                    "type": "integer"
                },
                "departmentID": {
                    "description": "DepartmentID 部门id",
                    "type": "integer"
                },
                "id": {
                    "description": "ID 数据自增 ID",
                    "type": "integer"
                },
                "name": {
                    "description": "Name 姓名",
                    "type": "string"
                },
                "updatedAt": {
                    "description": "UpdatedAt 更新时间",
                    "type": "integer"
                },
                "updatedBy": {
                    "description": "UpdatedBy 更新人id",
                    "type": "integer"
                }
            }
        },
        "dtouser.UserPageListItem": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "companyID": {
                    "description": "CompanyID 公司id",
                    "type": "integer"
                },
                "createdAt": {
                    "description": "CreatedAt 创建时间",
                    "type": "integer"
                },
                "createdBy": {
                    "description": "CreatedBy 创建人id",
                    "type": "integer"
                },
                "departmentID": {
                    "description": "DepartmentID 部门id",
                    "type": "integer"
                },
                "id": {
                    "description": "ID 数据自增 ID",
                    "type": "integer"
                },
                "name": {
                    "description": "Name 姓名",
                    "type": "string"
                },
                "updatedAt": {
                    "description": "UpdatedAt 更新时间",
                    "type": "integer"
                },
                "updatedBy": {
                    "description": "UpdatedBy 更新人id",
                    "type": "integer"
                }
            }
        },
        "dtouser.UserPageListResp": {
            "type": "object",
            "properties": {
                "list": {
                    "description": "List 数据列表",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtouser.UserPageListItem"
                    }
                },
                "total": {
                    "description": "Total 数据总条数",
                    "type": "integer"
                }
            }
        },
        "dtouser.UserUpdateReq": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "companyID": {
                    "description": "CompanyID 公司id",
                    "type": "integer"
                },
                "departmentID": {
                    "description": "DepartmentID 部门id",
                    "type": "integer"
                },
                "id": {
                    "description": "ID 数据自增 ID",
                    "type": "integer"
                },
                "name": {
                    "description": "Name 姓名",
                    "type": "string"
                }
            }
        },
        "gincontext.DtoRender": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "msg": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfodemo holds exported Swagger Info so clients can modify it
var SwaggerInfodemo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "demo",
	SwaggerTemplate:  docTemplatedemo,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfodemo.InstanceName(), SwaggerInfodemo)
}
