// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplateragforge = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/ragforge/chunk/pageList": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "知识块管理"
                ],
                "summary": "知识块列表分页",
                "parameters": [
                    {
                        "description": "知识块列表",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtochunk.ChunkPageListReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0,\"data\": \"ok\",\"msg\": \"success\"}",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/gincontext.DtoRender"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dtochunk.ChunkPageListResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/ragforge/chunk/search": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "知识块管理"
                ],
                "summary": "搜索知识块",
                "parameters": [
                    {
                        "description": "搜索知识块",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtochunk.ChunkSearchReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0,\"data\": \"ok\",\"msg\": \"success\"}",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/gincontext.DtoRender"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dtochunk.ChunkSearchResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/ragforge/kb/create": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "知识库管理"
                ],
                "summary": "创建知识库",
                "parameters": [
                    {
                        "description": "创建知识库",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtokb.KBCreateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0,\"data\": \"ok\",\"msg\": \"success\"}",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/gincontext.DtoRender"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dtokb.KBCreateResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/ragforge/kb/delete": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "知识库管理"
                ],
                "summary": "删除知识库",
                "parameters": [
                    {
                        "description": "删除知识库",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtokb.KBDeleteReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0,\"data\": \"ok\",\"msg\": \"删除成功\"}",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/gincontext.DtoRender"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/ragforge/kb/detail": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "知识库管理"
                ],
                "summary": "知识库详情",
                "parameters": [
                    {
                        "type": "integer",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0,\"data\": \"ok\",\"msg\": \"success\"}",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/gincontext.DtoRender"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dtokb.KBDetailResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/ragforge/kb/pageList": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "知识库管理"
                ],
                "summary": "知识库列表分页",
                "parameters": [
                    {
                        "description": "知识库列表",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtokb.KBPageListReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0,\"data\": \"ok\",\"msg\": \"success\"}",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/gincontext.DtoRender"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dtokb.KBPageListResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/ragforge/kb/update": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "知识库管理"
                ],
                "summary": "修改知识库",
                "parameters": [
                    {
                        "description": "修改知识库",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtokb.KBUpdateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0,\"data\": \"ok\",\"msg\": \"修改成功\"}",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/gincontext.DtoRender"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "string"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/ragforge/knowledge/createFile": {
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "知识管理"
                ],
                "summary": "从文件创建知识",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "知识库ID",
                        "name": "kbId",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "标题",
                        "name": "title",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "文件",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0,\"data\": \"ok\",\"msg\": \"success\"}",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/gincontext.DtoRender"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dtoknowledge.KnowledgeCreateResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/ragforge/knowledge/createManual": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "知识管理"
                ],
                "summary": "手动创建知识",
                "parameters": [
                    {
                        "description": "手动创建知识",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtoknowledge.KnowledgeCreateManualReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0,\"data\": \"ok\",\"msg\": \"success\"}",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/gincontext.DtoRender"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dtoknowledge.KnowledgeCreateResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/ragforge/knowledge/createUrl": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "知识管理"
                ],
                "summary": "从URL创建知识",
                "parameters": [
                    {
                        "description": "从URL创建知识",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtoknowledge.KnowledgeCreateURLReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0,\"data\": \"ok\",\"msg\": \"success\"}",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/gincontext.DtoRender"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dtoknowledge.KnowledgeCreateResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/ragforge/knowledge/detail": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "知识管理"
                ],
                "summary": "知识详情",
                "parameters": [
                    {
                        "type": "integer",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0,\"data\": \"ok\",\"msg\": \"success\"}",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/gincontext.DtoRender"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dtoknowledge.KnowledgeDetailResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/ragforge/knowledge/pageList": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "知识管理"
                ],
                "summary": "知识列表分页",
                "parameters": [
                    {
                        "description": "知识列表",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtoknowledge.KnowledgePageListReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0,\"data\": \"ok\",\"msg\": \"success\"}",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/gincontext.DtoRender"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dtoknowledge.KnowledgePageListResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/ragforge/qa/knowledgeChat": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "问答管理"
                ],
                "summary": "知识库问答",
                "parameters": [
                    {
                        "description": "知识库问答",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtoqa.KnowledgeChatReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0,\"data\": \"ok\",\"msg\": \"success\"}",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/gincontext.DtoRender"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dtoqa.KnowledgeChatResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/ragforge/qa/knowledgeChatStream": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "问答管理"
                ],
                "summary": "知识库问答流式",
                "parameters": [
                    {
                        "description": "知识库问答流式",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtoqa.KnowledgeChatReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "流式响应",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/v1/ragforge/session/create": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "会话管理"
                ],
                "summary": "创建会话",
                "parameters": [
                    {
                        "description": "创建会话",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtosession.SessionCreateReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0,\"data\": \"ok\",\"msg\": \"success\"}",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/gincontext.DtoRender"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dtosession.SessionCreateResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/ragforge/session/detail": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "会话管理"
                ],
                "summary": "会话详情",
                "parameters": [
                    {
                        "type": "integer",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0,\"data\": \"ok\",\"msg\": \"success\"}",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/gincontext.DtoRender"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dtosession.SessionDetailResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/v1/ragforge/session/pageList": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "会话管理"
                ],
                "summary": "会话列表分页",
                "parameters": [
                    {
                        "description": "会话列表",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtosession.SessionPageListReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"code\": 0,\"data\": \"ok\",\"msg\": \"success\"}",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/gincontext.DtoRender"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dtosession.SessionPageListResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dtochunk.ChunkPageListItem": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "createdAt": {
                    "description": "创建时间",
                    "type": "integer"
                },
                "createdBy": {
                    "description": "创建人id",
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "kbId": {
                    "type": "integer"
                },
                "knowledgeId": {
                    "type": "integer"
                },
                "seqId": {
                    "type": "integer"
                },
                "tokens": {
                    "type": "integer"
                },
                "updatedAt": {
                    "description": "更新时间",
                    "type": "integer"
                },
                "updatedBy": {
                    "description": "更新人id",
                    "type": "integer"
                }
            }
        },
        "dtochunk.ChunkPageListReq": {
            "type": "object",
            "properties": {
                "kbId": {
                    "type": "integer"
                },
                "knowledgeId": {
                    "type": "integer"
                },
                "page": {
                    "description": "页码",
                    "type": "integer"
                },
                "pageSize": {
                    "description": "每页数据条数",
                    "type": "integer",
                    "maximum": 1000
                }
            }
        },
        "dtochunk.ChunkPageListResp": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtochunk.ChunkPageListItem"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "dtochunk.ChunkSearchItem": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "knowledgeId": {
                    "type": "integer"
                },
                "score": {
                    "type": "number"
                },
                "seqId": {
                    "type": "integer"
                }
            }
        },
        "dtochunk.ChunkSearchReq": {
            "type": "object",
            "required": [
                "kbId",
                "query"
            ],
            "properties": {
                "kbId": {
                    "type": "integer"
                },
                "query": {
                    "type": "string"
                },
                "topK": {
                    "type": "integer"
                }
            }
        },
        "dtochunk.ChunkSearchResp": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtochunk.ChunkSearchItem"
                    }
                }
            }
        },
        "dtokb.KBCreateReq": {
            "type": "object",
            "required": [
                "kbType",
                "name"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "kbType": {
                    "$ref": "#/definitions/model.KBType"
                },
                "name": {
                    "type": "string"
                },
                "parserEngine": {
                    "$ref": "#/definitions/model.ParserEngine"
                }
            }
        },
        "dtokb.KBCreateResp": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "dtokb.KBDeleteReq": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "dtokb.KBDetailResp": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "description": "创建时间",
                    "type": "integer"
                },
                "createdBy": {
                    "description": "创建人id",
                    "type": "integer"
                },
                "creatorId": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "kbType": {
                    "$ref": "#/definitions/model.KBType"
                },
                "name": {
                    "type": "string"
                },
                "parserEngine": {
                    "$ref": "#/definitions/model.ParserEngine"
                },
                "tenantId": {
                    "type": "integer"
                },
                "updatedAt": {
                    "description": "更新时间",
                    "type": "integer"
                },
                "updatedBy": {
                    "description": "更新人id",
                    "type": "integer"
                }
            }
        },
        "dtokb.KBPageListItem": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "description": "创建时间",
                    "type": "integer"
                },
                "createdBy": {
                    "description": "创建人id",
                    "type": "integer"
                },
                "creatorId": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "kbType": {
                    "$ref": "#/definitions/model.KBType"
                },
                "name": {
                    "type": "string"
                },
                "parserEngine": {
                    "$ref": "#/definitions/model.ParserEngine"
                },
                "tenantId": {
                    "type": "integer"
                },
                "updatedAt": {
                    "description": "更新时间",
                    "type": "integer"
                },
                "updatedBy": {
                    "description": "更新人id",
                    "type": "integer"
                }
            }
        },
        "dtokb.KBPageListReq": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "page": {
                    "description": "页码",
                    "type": "integer"
                },
                "pageSize": {
                    "description": "每页数据条数",
                    "type": "integer",
                    "maximum": 1000
                }
            }
        },
        "dtokb.KBPageListResp": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtokb.KBPageListItem"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "dtokb.KBUpdateReq": {
            "type": "object",
            "required": [
                "id",
                "kbType",
                "name"
            ],
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "kbType": {
                    "$ref": "#/definitions/model.KBType"
                },
                "name": {
                    "type": "string"
                },
                "parserEngine": {
                    "$ref": "#/definitions/model.ParserEngine"
                }
            }
        },
        "dtoknowledge.KnowledgeCreateManualReq": {
            "type": "object",
            "required": [
                "content",
                "kbId",
                "title"
            ],
            "properties": {
                "content": {
                    "type": "string"
                },
                "kbId": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "dtoknowledge.KnowledgeCreateResp": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "dtoknowledge.KnowledgeCreateURLReq": {
            "type": "object",
            "required": [
                "kbId",
                "sourceUrl",
                "title"
            ],
            "properties": {
                "kbId": {
                    "type": "integer"
                },
                "sourceUrl": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "dtoknowledge.KnowledgeDetailResp": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "createdAt": {
                    "description": "创建时间",
                    "type": "integer"
                },
                "createdBy": {
                    "description": "创建人id",
                    "type": "integer"
                },
                "creatorId": {
                    "type": "integer"
                },
                "fileSize": {
                    "type": "integer"
                },
                "fileUrl": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "kbId": {
                    "type": "integer"
                },
                "parseStatus": {
                    "$ref": "#/definitions/model.ParseStatus"
                },
                "sourceUrl": {
                    "type": "string"
                },
                "tenantId": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/model.KnowledgeType"
                },
                "updatedAt": {
                    "description": "更新时间",
                    "type": "integer"
                },
                "updatedBy": {
                    "description": "更新人id",
                    "type": "integer"
                }
            }
        },
        "dtoknowledge.KnowledgePageListItem": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "description": "创建时间",
                    "type": "integer"
                },
                "createdBy": {
                    "description": "创建人id",
                    "type": "integer"
                },
                "creatorId": {
                    "type": "integer"
                },
                "fileSize": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "kbId": {
                    "type": "integer"
                },
                "parseStatus": {
                    "$ref": "#/definitions/model.ParseStatus"
                },
                "tenantId": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/model.KnowledgeType"
                },
                "updatedAt": {
                    "description": "更新时间",
                    "type": "integer"
                },
                "updatedBy": {
                    "description": "更新人id",
                    "type": "integer"
                }
            }
        },
        "dtoknowledge.KnowledgePageListReq": {
            "type": "object",
            "properties": {
                "kbId": {
                    "type": "integer"
                },
                "page": {
                    "description": "页码",
                    "type": "integer"
                },
                "pageSize": {
                    "description": "每页数据条数",
                    "type": "integer",
                    "maximum": 1000
                },
                "parseStatus": {
                    "$ref": "#/definitions/model.ParseStatus"
                },
                "type": {
                    "$ref": "#/definitions/model.KnowledgeType"
                }
            }
        },
        "dtoknowledge.KnowledgePageListResp": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtoknowledge.KnowledgePageListItem"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "dtoqa.KnowledgeChatReq": {
            "type": "object",
            "required": [
                "content",
                "kbId"
            ],
            "properties": {
                "content": {
                    "type": "string"
                },
                "kbId": {
                    "type": "integer"
                },
                "sessionId": {
                    "type": "integer"
                }
            }
        },
        "dtoqa.KnowledgeChatResp": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "sessionId": {
                    "type": "integer"
                }
            }
        },
        "dtosession.SessionCreateReq": {
            "type": "object",
            "required": [
                "kbId"
            ],
            "properties": {
                "kbId": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "dtosession.SessionCreateResp": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer"
                }
            }
        },
        "dtosession.SessionDetailResp": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "description": "创建时间",
                    "type": "integer"
                },
                "createdBy": {
                    "description": "创建人id",
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "isPinned": {
                    "type": "boolean"
                },
                "kbId": {
                    "type": "integer"
                },
                "tenantId": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "updatedAt": {
                    "description": "更新时间",
                    "type": "integer"
                },
                "updatedBy": {
                    "description": "更新人id",
                    "type": "integer"
                },
                "userId": {
                    "type": "integer"
                }
            }
        },
        "dtosession.SessionPageListItem": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "description": "创建时间",
                    "type": "integer"
                },
                "createdBy": {
                    "description": "创建人id",
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "isPinned": {
                    "type": "boolean"
                },
                "kbId": {
                    "type": "integer"
                },
                "tenantId": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                },
                "updatedAt": {
                    "description": "更新时间",
                    "type": "integer"
                },
                "updatedBy": {
                    "description": "更新人id",
                    "type": "integer"
                },
                "userId": {
                    "type": "integer"
                }
            }
        },
        "dtosession.SessionPageListReq": {
            "type": "object",
            "properties": {
                "kbId": {
                    "type": "integer"
                },
                "page": {
                    "description": "页码",
                    "type": "integer"
                },
                "pageSize": {
                    "description": "每页数据条数",
                    "type": "integer",
                    "maximum": 1000
                }
            }
        },
        "dtosession.SessionPageListResp": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dtosession.SessionPageListItem"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "gincontext.DtoRender": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "msg": {
                    "type": "string"
                },
                "requestID": {
                    "type": "string"
                }
            }
        },
        "model.KBType": {
            "type": "string",
            "enum": [
                "normal",
                "faq"
            ],
            "x-enum-varnames": [
                "KBTypeNormal",
                "KBTypeFAQ"
            ]
        },
        "model.KnowledgeType": {
            "type": "string",
            "enum": [
                "file",
                "url",
                "manual"
            ],
            "x-enum-varnames": [
                "KnowledgeTypeFile",
                "KnowledgeTypeURL",
                "KnowledgeTypeManual"
            ]
        },
        "model.ParseStatus": {
            "type": "string",
            "enum": [
                "pending",
                "parsing",
                "completed",
                "failed"
            ],
            "x-enum-varnames": [
                "ParseStatusPending",
                "ParseStatusParsing",
                "ParseStatusCompleted",
                "ParseStatusFailed"
            ]
        },
        "model.ParserEngine": {
            "type": "string",
            "enum": [
                "default",
                "docling",
                "tika"
            ],
            "x-enum-varnames": [
                "ParserEngineDefault",
                "ParserEngineDocling",
                "ParserEngineTika"
            ]
        }
    }
}`

// SwaggerInforagforge holds exported Swagger Info so clients can modify it
var SwaggerInforagforge = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "ragforge",
	SwaggerTemplate:  docTemplateragforge,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInforagforge.InstanceName(), SwaggerInforagforge)
}
