server:
  name: ragforge
  port: 8082
  env: dev

client:
  httpbingo:
    host: https://httpbingo.org
    module: httpbingo
    retry: 3
    timeout: 5s

log:
  default:
    logger_type: zap
    service: ragforge
    module: default
    level: info
    writers:
      - type: console
      - type: file
        dir: ../../../log
    extra_keys:
      - requestId
  gorm:
    logger_type: zap
    service: ragforge
    module: gorm
    level: debug
    writers:
      - type: console
      - type: file
        dir: ../../../log
    extra_keys:
      - requestId
  redis:
    logger_type: zap
    service: ragforge
    module: redis
    level: debug
    writers:
      - type: console
      - type: file
        dir: ../../../log
    extra_keys:
      - requestId

trace:
  enable: false
  service_version: ""
  sampler: traceidratio
  trace_id_ratio: 1.0
  otlp:
    endpoint: "127.0.0.1:4317"
    insecure: true
    timeout: 10s

storage:
  default_provider: local
  local:
    path_prefix: ""

db_configs:
  - url: "postgres://postgres:123456@127.0.0.1:5432/ragforge?sslmode=disable"
    service: ragforge

redis_config:
  service: ragforge
  addr: 127.0.0.1:6379
  password: 123456
  db: 0
  dial_timeout: 5s
  read_timeout: 3s
  write_timeout: 3s

es_configs: []
